#cp arith/Makefile arith/.
cp arith/Makefile bot/.
cp arith/Makefile equirec/.
cp arith/Makefile fomega/.
cp arith/Makefile fomsub/.
cp arith/Makefile fullequirec/.
cp arith/Makefile fullerror/.
cp arith/Makefile fullfomsub/.
cp arith/Makefile fullfomsubref/.
cp arith/Makefile fullfsub/.
cp arith/Makefile fullfsubref/.
cp arith/Makefile fullisorec/.
cp arith/Makefile fullomega/.
cp arith/Makefile fullpoly/.
cp arith/Makefile fullrecon/.
cp arith/Makefile fullref/.
cp arith/Makefile fullsimple/.
cp arith/Makefile fullsub/.
cp arith/Makefile fulluntyped/.
cp arith/Makefile fullupdate/.
cp arith/Makefile joinexercise/.
cp arith/Makefile letexercise/.
cp arith/Makefile purefsub/.
cp arith/Makefile rcdsubbot/.
cp arith/Makefile recon/.
cp arith/Makefile reconbase/.
cp arith/Makefile simplebool/.
cp arith/Makefile tyarith/.
cp arith/Makefile untyped/.
