build:
	cd arith; make
	cd untyped; make
	cd fulluntyped; make
	cd tyarith; make
	cd simplebool; make
	cd fullsimple; make
	cd bot; make
	cd fullerror; make
	cd fullref; make
	cd rcdsubbot; make
	cd fullsub; make
	cd reconbase; make
	cd recon; make
	cd fullrecon; make
	cd equirec; make
	cd fullequirec; make
	cd fullisorec; make
	cd fullpoly; make
	cd purefsub; make
	cd fullfsub; make
	cd fullfsubref; make
	cd fomega; make
	cd fullomega; make
	cd fomsub; make
	cd fullfomsub; make
	cd fullfomsubref; make
	cd fullupdate; make

gen:
	cd arith; make gen
	cd untyped; make gen
	cd fulluntyped; make gen
	cd tyarith; make gen
	cd simplebool; make gen
	cd fullsimple; make gen
	cd bot; make gen
	cd fullerror; make gen
	cd fullref; make gen
	cd rcdsubbot; make gen
	cd fullsub; make gen
	cd reconbase; make gen
	cd recon; make gen
	cd fullrecon; make gen
	cd equirec; make gen
	cd fullequirec; make gen
	cd fullisorec; make gen
	cd fullpoly; make gen
	cd purefsub; make gen
	cd fullfsub; make gen
	cd fullfsubref; make gen
	cd fomega; make gen
	cd fullomega; make gen
	cd fomsub; make gen
	cd fullfomsub; make gen
	cd fullfomsubref; make gen
	cd fullupdate; make gen

clean:
	cd arith; make clean
	cd untyped; make clean
	cd fulluntyped; make clean
	cd tyarith; make clean
	cd simplebool; make clean
	cd fullsimple; make clean
	cd bot; make clean
	cd fullerror; make clean
	cd fullref; make clean
	cd rcdsubbot; make clean
	cd fullsub; make clean
	cd reconbase; make clean
	cd recon; make clean
	cd fullrecon; make clean
	cd equirec; make clean
	cd fullequirec; make clean
	cd fullisorec; make clean
	cd fullpoly; make clean
	cd purefsub; make clean
	cd fullfsub; make clean
	cd fullfsubref; make clean
	cd fomega; make clean
	cd fullomega; make clean
	cd fomsub; make clean
	cd fullfomsub; make clean
	cd fullfomsubref; make clean
	cd fullupdate; make clean
